# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  DOCKER_USERNAME:
    description: 'The Docker Hub username.'
    required: true
  DOCKER_PASSWORD:
    description: 'The Docker Hub password.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.DOCKER_USERNAME }}
    - ${{ inputs.DOCKER_PASSWORD }}
