# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  hello:
    description: 'Test input'
    required: true
    default: '123'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.hello }}
