name: 'Wise Old Man NGINX Deploy Config'
description: 'Builds and deploys all the code on the Wise Old Man project.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  steps:
    - name: Build NGINX image
      run: |
        docker build . --file Dockerfile --tag wiseoldman/nginx-deploy-config:latest
        docker push wiseoldman/nginx-deploy-config:latest
